version: "3.8"

services:
  startup:
    build: ./automation
    command: ["python", "youtube.py"]
  api:
    build: ./backend
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
    restart: always
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/coding-crashkurse.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/coding-crashkurse.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - api
